const offerLink = "vnd.youtube://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqa3BpSmxkNGtmOVlqODhHLWhSUkpNNF9fWExuUXxBQ3Jtc0ttUGpCM210UzQ4MDdOODhNRmRGc0tPRF9MZ3FLdXpyWjRNSmxYcFl5a2lhSmpQOFhfTlVjUXdmOWo5U0hUNHJpWl9xMVp3eDhsbnZUaUxFMm9LWl8zbks3eDhOanhvTFJReGo3LWdTMDJWT3Y4OWdmTQ&q=https%3A%2F%2Fv.ht%2FRE4UM&html_redirect=1";



